### ISSUE TITLE
Link hints doesn't work on >= Chrome 80

### ISSUE THREAD

**Issue by ivanjermakov** [1995eaton/chromium-vim#721]
Any hint action (`f`, `F`, `q`, etc.) is ignored.

Does not work on `Chromium 80.0.3987.87 Arch Linux`, but works on `Chromium 79.0.3945.88 Arch Linux`.

**Comment by gnosthi** [comment]
Seconded. I can confirm that this is the case on MacOSX as well. 
The relevant error from the Chrome console is. 
```
Uncaught TypeError: main.createShadowRoot is not a function
    at hints.js:727
```

The stack:
```
(anonymous) | @ | hints.js:727
-- | -- | --
  | setTimeout (async) |   |  
  | Hints.create | @ | hints.js:679
  | createHint | @ | mappings.js:424
  | Mappings.convertToAction | @ | mappings.js:1152
  | down | @ | keys.js:733
  | (anonymous) | @ | keys.js:154
```

The offending line of code seems to be. 
```
  Hints.shadowDOM = main.createShadowRoot();
```
in hints.js

**Comment by Pronian** [comment]
I'm getting the `hints.js:727` error as well on `Windows 10 Version 80.0.3987.78 beta (64-bit)`

**Comment by ivanjermakov** [comment]
Duplicate of #716.
